apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: techtest
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-nginx
  namespace: techtest
  labels:
    app: nginx
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      automountServiceAccountToken: false
      containers:
      - name: nginx
        image: uzack12/nginx:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        env:
          - name: HOST_PORT
            valueFrom:
              configMapKeyRef:
                name: custom-config
                key: HOST_PORT
          - name: REVERSE_HOST
            valueFrom:
              configMapKeyRef:
                name: custom-config
                key: REVERSE_HOST